/*
 * File: app/view/User_SuggestedTab.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Scene.view.User_SuggestedTab', {
	extend: 'Ext.Container',
	alias: 'widget.user_suggestedtab',

	requires: [
		'Scene.view.User_SuggestedTabViewModel',
		'Ext.Toolbar',
		'Ext.Label',
		'Ext.dataview.List',
		'Ext.XTemplate'
	],

	viewModel: {
		type: 'user_suggestedtab'
	},
	layout: 'fit',

	items: [
		{
			xtype: 'toolbar',
			docked: 'top',
			items: [
				{
					xtype: 'label',
					centered: true,
					html: 'Scene'
				}
			]
		},
		{
			xtype: 'list',
			itemId: 'suggestedList',
			itemTpl: [
				'<div>{name} - {distance}{distanceUnit}</div>'
			],
			onItemDisclosure: 'itemDisclosure',
			bind: {
				store: '{SuggestedListStore}'
			}
		}
	],

	addNewScene: function(scene) {
		var store = this.getViewModel().getStore('SuggestedListStore');
		if(!store.findRecord('uniqueId',scene.uniqueId)){
			store.loadData([scene], true);
		}

	},

	removeScene: function(scene) {
		var store = this.getViewModel().getStore('SuggestedListStore');

		store.remove(store.findRecord('uniqueId',scene.uniqueId));
	},

	loadSuggestedList: function(suggestedList, accountInfo) {
		//console.log('here', suggestedList);

		this.getViewModel().getStore( 'SuggestedListStore' ).loadData( suggestedList );
		//console.log(this.getViewModel().getStore( 'SuggestedListStore' ));
		this.accountInfo = accountInfo;
	}

});