/*
 * File: app/view/User_interestedTab.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Scene.view.User_interestedTab', {
	extend: 'Ext.Container',
	alias: 'widget.user_interestedtab',

	requires: [
		'Scene.view.User_SuggestedTabViewModel1',
		'Ext.Toolbar',
		'Ext.Button',
		'Ext.Label',
		'Ext.dataview.List',
		'Ext.XTemplate',
		'Ext.ActionSheet'
	],

	viewModel: {
		type: 'user_interestedtab'
	},
	layout: 'fit',
	defaultListenerScope: true,

	items: [
		{
			xtype: 'toolbar',
			docked: 'top',
			items: [
				{
					xtype: 'button',
					text: '| | |'
				},
				{
					xtype: 'label',
					centered: true,
					html: 'Scene'
				},
				{
					xtype: 'button',
					itemId: 'mybutton1',
					right: 0,
					text: 'Test Button',
					listeners: {
						tap: 'onMybutton1Tap'
					}
				}
			]
		},
		{
			xtype: 'list',
			itemId: 'suggestedList',
			itemTpl: [
				'<div>{name} - {distance}{distanceUnit}</div>'
			],
			onItemDisclosure: 'itemDisclosure',
			bind: {
				store: '{SuggestedListStore}'
			}
		},
		{
			xtype: 'actionsheet',
			height: '100%',
			hidden: true,
			width: '40%',
			enter: 'left',
			exit: 'left',
			items: [
				{
					xtype: 'list',
					itemTpl: [
						'<div>List Item {string}</div>'
					]
				}
			]
		}
	],

	onMybutton1Tap: function(button, e, eOpts) {
		AERP.Ajax.request(
			{
				url:'/SceneRequest/controllerTest',
				params: {
					'data': 'hello',
				},
				success:function(response) {

				},
				failure:function(response) {

				},
				scope:this
			});
	},

	loadSuggestedList: function(suggestedList, accountInfo) {
		this.getViewModel().getStore( 'SuggestedListStore' ).loadData( suggestedList );
		this.accountInfo = accountInfo;
	},

	itemDisclosure: function(record) {
		//console.log(record.data);

		//console.log(this.queryById('suggestedList'));
		if(!this.SceneInfoPanel){
			this.SceneInfoPanel = Ext.create('Scene.view.SceneInfoPanel');
			this.SceneInfoPanel.accountInfo = this.accountInfo;
		}
		//console.log(this.SceneInfoPanel);
		this.SceneInfoPanel.currentScene = record.data;
		this.SceneInfoPanel.show();
	}

});