/*
 * File: app/view/CompanyView.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('company.view.CompanyView', {
	extend: 'Ext.container.Container',
	alias: 'widget.companyview',

	requires: [
		'company.view.CompanyViewViewModel',
		'Ext.container.Container',
		'Ext.button.Button',
		'Ext.form.Label',
		'Ext.form.field.Text'
	],

	viewModel: {
		type: 'companyview'
	},
	height: '100%',
	width: '100%',
	layout: 'fit',
	defaultListenerScope: true,

	items: [
		{
			xtype: 'container',
			flex: 0.25,
			items: [
				{
					xtype: 'button',
					text: 'Create event'
				},
				{
					xtype: 'container',
					height: '25%',
					width: '25%',
					items: [
						{
							xtype: 'label',
							text: 'To search for an event, enter the name and address'
						}
					]
				},
				{
					xtype: 'textfield',
					itemId: 'locationName',
					fieldLabel: 'Name'
				},
				{
					xtype: 'textfield',
					itemId: 'locationAddress',
					fieldLabel: 'Address'
				},
				{
					xtype: 'button',
					text: 'Search',
					listeners: {
						click: 'onButtonClick'
					}
				}
			]
		},
		{
			xtype: 'container',
			flex: 1
		}
	],

	onButtonClick: function(button, e, eOpts) {
		    AERP.Ajax.request({
		    url:'/SceneRequest/handleCompanySearch',
		    params: {
		        locationName: this.queryById('locationName').getValue(),
		        locationAddress: this.queryById('locationAddress').getValue(),
		    },
		    success:function(response) {
		        console.log(response);
		    },
		    failure:function(response) {

		    },
		    scope:this
		});
	}

});