/*
 * File: app/view/LoginView.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('company.view.LoginView', {
	extend: 'Ext.container.Container',
	alias: 'widget.loginview',

	requires: [
		'company.view.LoginViewViewModel',
		'Ext.form.field.Text',
		'Ext.button.Button'
	],

	viewModel: {
		type: 'loginview'
	},
	height: 250,
	width: 400,
	defaultListenerScope: true,

	items: [
		{
			xtype: 'textfield',
			itemId: 'email',
			fieldLabel: 'Email'
		},
		{
			xtype: 'textfield',
			itemId: 'password',
			fieldLabel: 'Password'
		},
		{
			xtype: 'button',
			text: 'Login',
			listeners: {
				click: 'onButtonClick'
			}
		}
	],

	onButtonClick: function(button, e, eOpts) {
		this.fireEvent('login', this.queryById('email').getValue(),  this.queryById('password').getValue());
		/*
		AERP.Ajax.request({
		           url:'/SceneRequest/handleNonFacebookLogin',
		           params: {
		               email: this.queryById('email').getValue(),
		               pass: this.queryById('password').getValue(),
		               latitude: 42.0278208,
		               longitude: -93.64894819999999
		           },
		           success:function(response) {
		               if(!this.CompanyViewPanel){
		                  this.CompanyViewPanel = Ext.create('company.view.CompanyView');
		                 }
		               this.CompanyViewPanel.show();
		           },
		           failure:function(response) {

		           },
		           scope:this
		         });
		         */
	}

});