/*
 * File: app/view/MyContainer.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('company.view.MyContainer', {
	extend: 'Ext.container.Container',
	alias: 'widget.mycontainer',

	requires: [
		'company.view.MyContainerViewModel',
		'Ext.container.Container',
		'Ext.button.Button',
		'Ext.form.Label',
		'Ext.form.field.Text'
	],

	viewModel: {
		type: 'mycontainer'
	},
	height: '100%',
	width: '100%',
	layout: 'fit',

	items: [
		{
			xtype: 'container',
			flex: 0.25,
			items: [
				{
					xtype: 'button',
					text: 'Create event'
				},
				{
					xtype: 'container',
					height: '25%',
					width: '25%',
					items: [
						{
							xtype: 'label',
							text: 'To search for an event, enter the name and address'
						}
					]
				},
				{
					xtype: 'textfield',
					fieldLabel: 'Name'
				},
				{
					xtype: 'textfield',
					fieldLabel: 'Address'
				},
				{
					xtype: 'button',
					text: 'Search'
				}
			]
		},
		{
			xtype: 'container',
			flex: 1
		}
	]

});