/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Scene.view.MainView', {
	extend: 'Ext.tab.Panel',
	alias: 'widget.mainview',

	requires: [
		'Scene.view.MainViewViewModel',
		'Scene.view.User_SuggestedTab',
		'Scene.view.User_SettingsTab',
		'Ext.Container'
	],

	viewModel: {
		type: 'mainview'
	},
	tabBarPosition: 'bottom',
	defaultListenerScope: true,

	items: [
		{
			xtype: 'user_suggestedtab',
			itemId: 'suggestedTab',
			title: 'Suggested',
			listeners: {
				interestedEvent2: 'onContainerInterestedEvent2',
				disinterestedEvent2: 'onContainerDisinterestedEvent2'
			}
		},
		{
			xtype: 'user_settingstab',
			itemId: 'user_settingstab',
			title: 'Settings',
			listeners: {
				logoutSuccess: 'onContainerLogoutSuccess'
			}
		},
		{
			xtype: 'user_suggestedtab',
			itemId: 'interestedTab',
			title: 'Interested',
			listeners: {
				disinterestedEvent2: 'onContainerDisinterestedEvent21',
				interestedEvent2: 'onContainerInterestedEvent21'
			}
		}
	],

	onContainerInterestedEvent2: function(scene) {
		this.queryById('interestedTab').addNewScene(scene);
	},

	onContainerDisinterestedEvent2: function(scene) {
		this.queryById('interestedTab').removeScene(scene);
	},

	onContainerLogoutSuccess: function() {
		Ext.Viewport.setActiveItem(this.loginPanel);
	},

	onContainerDisinterestedEvent21: function(container) {
		this.queryById('interestedTab').removeScene(scene);
	},

	onContainerInterestedEvent21: function(container) {
		this.queryById('interestedTab').addNewScene(scene);
	},

	loadSuggestedList: function(accountInfo, suggestedList, interestedList) {
		//console.log("here_loadSuggestedList");
		this.accountInfo = accountInfo;
		this.suggestedList = suggestedList;

		this.interestedList = interestedList;
		this.queryById('suggestedTab').loadSuggestedList(this.suggestedList, this.accountInfo);
		//console.log(this.accountInfo);
		this.queryById('interestedTab').loadSuggestedList(this.interestedList, this.accountInfo);

	},

	itemDisclosure: function(record) {
		var me = this;
		if(!this.SceneInfoPanel){
			this.SceneInfoPanel = Ext.create('Scene.view.SceneInfoPanel',{
				listeners: {
					'interestedEvent':function(scene){
						//console.log('stage 2');
						me.queryById('interestedTab').addNewScene(scene);
					},
					'disinterestedEvent':function(scene){
						me.queryById('interestedTab').removeScene(scene);
					}
				}
			});
			this.SceneInfoPanel.accountInfo = this.accountInfo;
		}
		//console.log(this.SceneInfoPanel);
		this.SceneInfoPanel.currentScene = record.data;
		this.SceneInfoPanel.show();

	}

});