/*
 * File: app/view/SceneInfoPanel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Scene.view.SceneInfoPanel', {
	extend: 'Ext.ActionSheet',
	alias: 'widget.sceneinfopanel',

	requires: [
		'Scene.view.SceneInfoPanelViewModel',
		'Ext.Label',
		'Ext.Button',
		'Ext.TitleBar'
	],

	viewModel: {
		type: 'sceneinfopanel'
	},
	height: '100%',
	layout: 'vbox',
	defaultListenerScope: true,

	items: [
		{
			xtype: 'container',
			height: '40px',
			layout: 'vbox',
			items: [
				{
					xtype: 'label',
					flex: 1,
					itemId: 'address',
					html: 'address'
				},
				{
					xtype: 'label',
					flex: 1,
					itemId: 'distance',
					html: 'distance'
				}
			]
		},
		{
			xtype: 'container',
			height: '100px',
			layout: 'hbox',
			items: [
				{
					xtype: 'container',
					height: '100%',
					itemId: 'scene-image',
					width: '100px'
				}
			]
		},
		{
			xtype: 'container',
			flex: 1,
			itemId: 'desc'
		},
		{
			xtype: 'container',
			items: [
				{
					xtype: 'label',
					html: 'Are you interested?'
				},
				{
					xtype: 'container',
					height: '45px',
					items: [
						{
							xtype: 'button',
							height: '100%',
							itemId: 'mybutton7',
							margin: '0 5 0 0',
							text: '<i class="fa fa-smile-o" aria-hidden="true" style="font-size:50px"></i>',
							listeners: {
								tap: 'onMybutton7Tap'
							}
						},
						{
							xtype: 'button',
							height: '100%',
							itemId: 'mybutton8',
							text: '<i class="fa fa-frown-o" aria-hidden="true"  style="font-size:50px"></i>',
							listeners: {
								tap: 'onMybutton8Tap'
							}
						}
					]
				}
			]
		},
		{
			xtype: 'container',
			items: [
				{
					xtype: 'label',
					html: 'Have you been here before?'
				},
				{
					xtype: 'container',
					height: '45px',
					items: [
						{
							xtype: 'button',
							height: '100%',
							itemId: 'mybutton7',
							margin: '0 5 0 0',
							text: '<i class="fa fa-smile-o" aria-hidden="true" style="font-size:50px"></i>',
							listeners: {
								tap: 'onMybutton7Tap1'
							}
						},
						{
							xtype: 'button',
							height: '100%',
							itemId: 'mybutton8',
							text: '<i class="fa fa-frown-o" aria-hidden="true"  style="font-size:50px"></i>',
							listeners: {
								tap: 'onMybutton8Tap1'
							}
						}
					]
				}
			]
		},
		{
			xtype: 'container',
			height: '60px'
		},
		{
			xtype: 'titlebar',
			itemId: 'titleBackBar',
			docked: 'top',
			items: [
				{
					xtype: 'button',
					itemId: 'mybutton11',
					text: '<',
					listeners: {
						tap: 'onMybutton11Tap'
					}
				}
			]
		}
	],
	listeners: {
		show: 'onActionsheetShow'
	},

	onMybutton7Tap: function(button, e, eOpts) {
		//console.log(this.accountInfo,this.currentScene);

		AERP.Ajax.request({
			url:'/SceneRequest/user_interested',
			params: {
				account_id:this.accountInfo.id,
				key: this.currentScene.uniqueId,
				companyName: this.currentScene.name
			},
			success:function(response) {
				this.fireEvent('interestedEvent', this.currentScene);
			},
			failure:function(response) {

			},
			scope:this
		});
	},

	onMybutton8Tap: function(button, e, eOpts) {
		AERP.Ajax.request({
			url:'/SceneRequest/user_disinterested',
			params: {
				account_id:this.accountInfo.id,
				key: this.currentScene.uniqueId,
				companyName: this.currentScene.name
			},
			success:function(response) {
				this.fireEvent('disinterestedEvent', this.currentScene);
			},
			failure:function(response) {

			},
			scope:this
		});
	},

	onMybutton7Tap1: function(button, e, eOpts) {
		AERP.Ajax.request({
			url:'/SceneRequest/user_like',
			params: {
				account_id:this.accountInfo.id,
				key: this.currentScene.uniqueId,
				companyName: this.currentScene.name
			},
			success:function(response) {
				//console.log(response);
			},
			failure:function(response) {

			},
			scope:this
		});
	},

	onMybutton8Tap1: function(button, e, eOpts) {
		AERP.Ajax.request({
			url:'/SceneRequest/user_dislike',
			params: {
				account_id:this.accountInfo.id,
				key: this.currentScene.uniqueId,
				companyName: this.currentScene.name
			},
			success:function(response) {
				//console.log(response);
			},
			failure:function(response) {

			},
			scope:this
		});
	},

	onActionsheetShow: function(component, eOpts) {
		this.loadForm();
	},

	onMybutton11Tap: function(button, e, eOpts) {
		this.hide();
	},

	loadForm: function() {
		this.queryById('titleBackBar').setTitle(this.currentScene.name);
		this.queryById("address").setHtml(this.currentScene.address);
		this.queryById("distance").setHtml(this.currentScene.distance + this.currentScene.distanceUnit);
		this.queryById("scene-image").setHtml(
			'<div style="height:100%;width:100%;background-image:url('+"'"+this.currentScene.image_url_y +"'"+ ')"></div>');

		this.queryById("desc").setHtml(this.currentScene.snippet_text_y);
	}

});