/*
 * File: app/view/SuggestedListItem.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Scene.view.SuggestedListItem', {
	extend: 'Ext.dataview.ListItem',
	alias: 'widget.suggestedlistitem',

	requires: [
		'Scene.view.SuggestedListItemViewModel',
		'Ext.Container'
	],

	viewModel: {
		type: 'suggestedlistitem'
	},
	height: '160px',
	layout: 'vbox',

	items: [
		{
			xtype: 'component',
			itemId: 'imageContainer',
			html: 'This is an image',
			maxHeight: 100,
			minHeight: 100
		},
		{
			xtype: 'container',
			flex: 1,
			html: 'Name | Location'
		}
	],

	updateRecord: function(record) {
		// Provide an implementation to update this container's child items
	}

});