/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('company.view.MyViewport', {
	extend: 'Ext.container.Viewport',
	alias: 'widget.myviewport',

	requires: [
		'company.view.MyViewportViewModel',
		'company.view.LoginView',
		'company.view.CompanyView',
		'Ext.container.Container'
	],

	viewModel: {
		type: 'myviewport'
	},
	height: 250,
	width: 400,
	defaultListenerScope: true,

	items: [
		{
			xtype: 'loginview',
			itemId: 'loginView',
			listeners: {
				login: 'onContainerLogin'
			}
		},
		{
			xtype: 'companyview',
			hidden: true,
			itemId: 'companyView'
		}
	],

	onContainerLogin: function(email, password) {
		AERP.Ajax.request({
		    url:'/SceneRequest/handleNonFacebookLogin',
		    params: {
		        email: email,
		        pass: password,
		        latitude: 42.0278208,
		        longitude: -93.64894819999999
		    },
		    success:function(response) {
		        this.queryById('loginView').hide();
		        this.queryById('companyView').show();
		    },
		    failure:function(response) {

		    },
		    scope:this
		});
	}

});